version: '3.8'

services:
  prediction-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prediction-system-server
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - prediction-network
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
      - ./db-init/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    env_file:
      - .env
    networks:
      - prediction-network

networks:
  prediction-network:
    driver: bridge
